development:
  adapter: postgresql
  encoding: unicode
  database: reveal-api_development
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: reveal-api_test
  pool: 5
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: reveal-api_production
  pool: 5
  password:
